[project]
name = "modbus-slave"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "modbus>=3.2",
    "pymodbus>=3.0.1",
]
